server:
  port: 8080
spring:
  application:
    name: community
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/housing?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
alipay:
  appId: 9021000133661913
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCTOmBXpDY+mlwhQVTPcumQqFtHEJy7fxsEL4PMSPmp6jLopD+2HQVfNxnEzMvabzkRJhwrJlL+XGXeiftM0GOURKXkoGRYNqSm5wWKAtZvqjjd3bOkJGnMaP5073piuCBg+aZjSVRAv2tIap95m/96kLFeVfZuz7SeKulM3d380gomUHIfVvHa8MIdnEC5al9d4+7TjtwOIpfktOXKq7Q26yvBMiF8UTVihbfwz7waN5kqmAjZinbnH2otXg4bNHyKnYNFyzhRAL5Pfe7GOfMPdcn3kHdA1Tv7xdVe2V2L64rbvTm1ieWGTyowOx6z4787RyVLRZmaNh5toQX507hvAgMBAAECggEBAJDZ63Xu40u+lQxG+clMls2zRnLpvjqeuJbqpLJ1zeVFvaa0CtcDQIjIbnr4v0v/B9d+dlJh11/YyoUjnnKZyI9U5x7ES1WbFW38d6+sUQv2HxLykE7bYJgzaL7l6rR70ad3mCOxPsqhSk0qUhLUz4voFgnpa5bkliDTuUveMg0Nn5hvDyGd+BO5iTQzxpCKCiR9oTb9gd60vnnN06TV3WqMoVZnCiQOdJY6Jh/fjhO9VQ+S+wgdi1wYZwASi7AdurqOwPPb/SjLcVIkh0GK5WetCUvNvWBbC2f249TWKFII+AXDUEArcsra66ILgJvH8CtjazDmGxZ5k1gCK3c7kkkCgYEAyUe3qq82QVqKpIcVX6vNSwQDrqjAGhi6t7hiEw9JflHvKQmKBFYg7GdyQiO3ITmOsf/+MS7/nWs56lbDb+S5aTKgBdsKtXY0rS2dMFs8Lm8t0TI5Y2B7gcS5OWJIokBB0IN5AaGJMCSt2ccXSLpfj+Pc+lFhUJZNfHrdvcXPHq0CgYEAu0DZzl0LzZG5CAKyhn9nTaHaq2sEJYlXEZjXlXCnJUTtGUKz2Am9OUJ7jkAFcMygyNiA08ZhNhacioErUenI/TJCN60v36QetTvaI8BQ6frw2xsDyMk2xyZyxQAurUeZqfXirVKcg7pPwi/yjtuZG8hUzS1JMKe/chKA0lHi4wsCgYB1gkYrAtGlA+wPM8H5sb5Pvk88B87nLWrM2XuAbxtUARekGKqX74SXH6moDVvbrNOu/an0IuEekTwloHPG/nx0exbLdF7jI9iLBidP1OPkpAnWqQCyEODqGOSeKNAI0YTa6/aYSitijPdmPgJM9mnWAoy/IwWyW51vP/f20+YgnQKBgQCevEbnDTFoPlPgWokEQxRLVx2LmtiVCWvp2utGH41RprBnbYgPZ5Ik7BrZZ6Q1DwJtwDrVS6I0u85QC1exxMFBAk3n7MRcjUAK2oX9MJZnAvcShkAbAZeSEyHPpmvrMHsu/OX/j7xmXpYmQ4cXW0jbqGNa2zzkJg/An7bck9YGKQKBgQCLc8xDwFEH9x6FA4JCR1zANO1SL6Hjgt1lyxk3SQaAGQboGOJff7wW6bDv/kUXNGbPgBTC07uwQcXtdp09SS1OHjoyASiYAouCAlJnZmx38bLB1FuQAOO14/kx4Jyxo6Ra3MNRO6tr9mf4FJRSLji4ap8dBJupl77uaRtJA5lnNA==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1c83HHUmnqZ87PUyyBVvJp6rOHBgWixByChBYu5Pdr3nAbi/4pzeHqFdSo7ta2IQEYbUlKs0OUpNlA5LGvSMnQPZn8nE8ItOX+DErYDEEE2lEXfLFaP88DRdyJtWRwvRoeF6wfP/1PCzGzFoVhiQpw9SoxLkRxpx4xLlOia2L/PdtDeB+6gH31ARikBkStmCNv4vh3rdOJmx7fXCWT/ml/X/u/jo1UoMIq9O9buP9OoqQzAp/vWVCLTeZBybJ6KgewlEWSIqRDfvESB6/yuUtn8VSRl0nVz5OjyDPuMRpRehceUANNtCMoSpkyZMBOA4d2HyY8/1lVh5WFEeZhEFNwIDAQAB
  notifyUrl:  http://4wpwzp.natappfree.cc/backend/page/order/list.html
